spring.application.name=Ecommerce

#database config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.hbm2ddl.auto=update

#spring.datasource.url=jdbc:mysql://localhost:3306/ecomdb
#spring.datasource.username=root
#spring.datasource.password=projectspring.datasource.username=${DB_USERNAME}

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ecomdb}
spring.datasource.username=root
spring.datasource.password=MYSQL_ROOT_PASSWORD

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql= true

#server.port=5454

spring.mail.host=smtp.gmail.com
spring.mail.port=587

#spring.mail.username=hs2312hemant@gmail.com
#spring.mail.password=yiwd fwav rzbz ogds

spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect